### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by CircuitSetup** [elshnkhll/DTMF_on_MAX98357A#2]
Thanks so much for publishing this! It is very useful for what I'm making. 

However, I noticed that the delay between triggering the tone, and it actually playing is about 2 seconds. Any ideas on speeding this up?

**Comment by elshnkhll** [comment]
Yes, you can tweek delay(***); values in the code to optimize it, use 240 MHz mode, remove some unnecessary Serial.println("**"); statements to speed it up.
